<?php

namespace MovieBundle\Repository;

/**
 * ActionYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionYearRepository extends \Doctrine\ORM\EntityRepository
{
}
